# Generated by Django 4.0.3 on 2022-03-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Ваше имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваша электронная почта')),
                ('comments', models.TextField(verbose_name='Ваш отзыв')),
            ],
        ),
    ]
